name: verify unit tests count

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  collect-and-verify:
    runs-on: [ "ubuntu-20.04" ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install system requirements
        run: |
          make ubuntu-requirements

      - name: install requirements
        run: |
          make test-requirements

      - name: verify unit tests count
        uses: ./.github/actions/verify-tests-count
